### ISSUE TITLE
Suggestion: one repo per package

### ISSUE THREAD

**Issue by SachaG** [Meteor-Alt/accounts#3]
I don't know how others work on packages locally, but I use the PACKAGE_DIRS technique personally. So when I want to work on a package, I usually just clone the repo into my package directory and it just works. 

Since this repo contains two packages though, I can't really do that. It's not a *huge* problem, but I was thinking if you want to get more contributors it might be good to make it even easier to get started cloning the packages? Curious to know what you think.

**Comment by emmostrom** [comment]
The directory structure was set up to match how MDG does some of their repos.  I understand the issue you are having but I'm not going to break it out at this time.

I don't see a lot of people making pull requests to this repo since it was designed to be customizable.  I expect most changes to just be overrides of parts a developer want to be different.  If I do see a lot of useful PR's coming in I'd be open to splitting it out.

If you're on Linux I think you can use symbolic links in your PACKAGE_DIRS directory.

**Comment by SachaG** [comment]
Well my point was that this will *prevent* PRs from coming in.
